#ifndef __EPD_DASHBOARD_PROTOCOL_H__
#define __EPD_DASHBOARD_PROTOCOL_H__

#include <stdint.h>

#define EPD_DASH_PROTOCOL_VERSION 0x01
#define EPD_DASH_MAX_SCHEDULES 2
#define EPD_DASH_MAX_FOODS 4
#define EPD_DASH_MAX_BITMAP_BYTES 1024

typedef enum {
    EPD_CMD_DASH_CAPS = 0x40,
    EPD_CMD_DASH_BEGIN = 0x41,
    EPD_CMD_DASH_BITMAP = 0x42,
    EPD_CMD_DASH_COMMIT = 0x43,
    EPD_CMD_DASH_ABORT = 0x44,
    EPD_NOTIFY_DASH_RESPONSE = 0xC0,
} epd_dashboard_command_t;

typedef enum {
    EPD_DASH_STATUS_OK = 0x00,
    EPD_DASH_STATUS_BAD_VERSION = 0x01,
    EPD_DASH_STATUS_BAD_LENGTH = 0x02,
    EPD_DASH_STATUS_BAD_STATE = 0x03,
    EPD_DASH_STATUS_BAD_TRANSACTION = 0x04,
    EPD_DASH_STATUS_BAD_SLOT = 0x05,
    EPD_DASH_STATUS_BAD_BITMAP = 0x06,
    EPD_DASH_STATUS_BAD_CRC = 0x07,
    EPD_DASH_STATUS_NO_MEMORY = 0x08,
    EPD_DASH_STATUS_BUSY = 0x09,
    EPD_DASH_STATUS_UNSUPPORTED = 0x0A,
    EPD_DASH_STATUS_TIMEOUT = 0x0B,
} epd_dashboard_status_t;

typedef enum {
    EPD_DASH_ASSET_SCHEDULE_0 = 0x00,
    EPD_DASH_ASSET_SCHEDULE_1 = 0x01,
    EPD_DASH_ASSET_FOOD_0 = 0x10,
    EPD_DASH_ASSET_FOOD_1 = 0x11,
    EPD_DASH_ASSET_FOOD_2 = 0x12,
    EPD_DASH_ASSET_FOOD_3 = 0x13,
} epd_dashboard_asset_id_t;

enum {
    EPD_DASH_BITMAP_BEGIN = 0x01,
    EPD_DASH_BITMAP_END = 0x02,
    EPD_DASH_BITMAP_INVERT = 0x04,
};

enum {
    EPD_DASH_COMMIT_REFRESH = 0x01,
    EPD_DASH_COMMIT_SLEEP = 0x02,
};

#endif
